### ISSUE TITLE
Errors from the tool after running it.

### ISSUE THREAD

**Issue by guyhacker** [CyberCX-DFIR/usnjrnl_rewind#1]
<img width="676" alt="Capture5" src="https://github.com/CyberCX-DFIR/usnjrnl_rewind/assets/12577261/f0b6b964-6d8a-45b0-8fff-5144dc590447">

**Comment by guyhacker** [comment]
<img width="628" alt="Capture6" src="https://github.com/CyberCX-DFIR/usnjrnl_rewind/assets/12577261/c8e63df3-b99b-4919-9dad-9c761bcae962">

I got this new error this morning, no idea why.
Regards.

**Comment by ydkhatri** [comment]
> <img alt="Capture5" width="676" src="https://private-user-images.githubusercontent.com/12577261/339151749-f0b6b964-6d8a-45b0-8fff-5144dc590447.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNzAzNTgsIm5iZiI6MTcyMDI3MDA1OCwicGF0aCI6Ii8xMjU3NzI2MS8zMzkxNTE3NDktZjBiNmI5NjQtNmQ4YS00NWIwLThmZmYtNTE0NGRjNTkwNDQ3LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDEyNDczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OGM1OGJjM2YyZWQxYmQwNTFlNDY5M2NlZDdmMTlkYWNhNGU1ZGZmZjUyYTc0NTFmNDQxYmM0Yzc1MWE5YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SQ1ABCWELpLZ38YSa8ZG4hIjbjTD0WylhYKg_KJi6dU">

Can you post the full command line used and make sure that the MFT parsed output file you are providing (as input to this script) has data in it as that error can occur if you passed to it an empty file.

**Comment by ydkhatri-cybercx** [comment]
Closing for lack of response.
